name: "Helm Chart Release"
description: "Package and release helm charts to an S3 bucket"
inputs:
  skip-helm-setup:
    description: "Skip the helm setup process if it has been run in the same job already"
    required: false
    default: "false"
  skip-aws-setup:
    description: "Skip the AWS setup process if it has been run in the same job already"
    required: false
    default: "false"
  aws-access-key-id:
    description: "The AWS access key with permissions to push to S3"
    required: true
  aws-secret-access-key:
    description: "The AWS secret access key"
    required: true
  aws-region:
    description: "The AWS region where there S3 bucket is created"
    required: true
  chart-directory:
    description: "The directory where the helm charts are stored"
    required: true
  s3-bucket:
    description: "The S3 bucket to push to"
    required: true
  chart-version:
    description: "The chart version number to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Helm
      if: ${{ inputs.skip-helm-setup == 'false' }}
      uses: azure/setup-helm@v3

    - name: Configure AWS Credentials
      if: ${{ inputs.skip-aws-setup == 'false' }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Helm S3 Plugin
      if: ${{ inputs.skip-helm-setup == 'false' }}
      shell: bash
      run: |
        helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.14.0

    - shell: bash
      run: |
        export CHART_DIR=${{ inputs.chart-directory }}
        helm repo add aruba-uxi ${{ inputs.s3-bucket }}
        helm dependency update ${CHART_DIR}
        helm package ${CHART_DIR} --destination chart-packages --version ${{ inputs.chart-version }}
        helm s3 push chart-packages/$(ls chart-packages) aruba-uxi --ignore-if-exists
